# Generated by Django 4.2.23 on 2026-08-22 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('appointment', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('checked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_ended_at', models.DateTimeField(blank=True, null=True)),
                ('visit_type', models.CharField(choices=[('appointment', 'Scheduled appointment'), ('walk_in', 'Walk-in'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency')], default='appointment', max_length=16)),
                ('chief_complaint', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='appointment.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['checked_in_at'],
                'indexes': [models.Index(fields=['status', 'checked_in_at'], name='visits_visi_status_fa8866_idx')],
            },
        ),
    ]
