# Generated by Django 4.2.23 on 2025-09-11 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_hospital_alter_booking_options_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('block_type', models.CharField(choices=[('doctor', 'Doctor Unavailable'), ('maintenance', 'Maintenance/Cleaning'), ('emergency', 'Emergency Block'), ('holiday', 'Holiday/Leave'), ('training', 'Staff Training'), ('other', 'Other Reason')], default='other', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for blocking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocks', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='dashboard.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='dashboard.hospital')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['hospital', 'date', 'is_active'], name='dashboard_b_hospita_788afa_idx'), models.Index(fields=['doctor', 'date', 'is_active'], name='dashboard_b_doctor__12f30b_idx')],
            },
        ),
    ]
