# Generated by Django 4.2.23 on 2026-08-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_hospital_alter_customuser_phone_and_more'),
        ('dashboard', '0003_blockedtimeslot'),
    ]

    operations = [
        migrations.DeleteModel(name='Booking'),
        migrations.DeleteModel(name='BlockedTimeSlot'),
        migrations.DeleteModel(name='DoctorManagement'),
        migrations.DeleteModel(name='HospitalManagement'),
        migrations.DeleteModel(name='Appointment'),
        migrations.DeleteModel(name='Service'),
        migrations.DeleteModel(name='Doctor'),
        migrations.DeleteModel(name='Hospital'),
    ]
