# Generated by Django 4.2.23 on 2025-09-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_hospital_alter_booking_options_alter_booking_status_and_more'),
        ('accounts', '0002_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.hospital'),
        ),
    ]
