# Generated by Django 4.2.23 on 2025-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('hospital_admin', 'Hospital Admin'), ('staff', 'Hospital Staff')], default='patient', max_length=20),
        ),
    ]
