# Generated by Django 4.2.23 on 2026-08-22 18:26

from django.db import migrations, models


def normalise_existing_accounts(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    User.objects.filter(phone__isnull=True).update(phone='')
    User.objects.filter(role='admin').update(role='system_admin')
    User.objects.filter(role='hospital_admin').update(role='clinic_admin')
    User.objects.filter(role='staff').update(role='receptionist')
    # Previous public-booking accounts must never silently become clinic staff.
    User.objects.filter(role='patient').update(role='receptionist', is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(normalise_existing_accounts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customuser',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff/profiles/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('clinic_admin', 'Clinic Administrator'), ('optometrist', 'Optometrist'), ('ophthalmologist', 'Ophthalmologist'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('optician', 'Optician'), ('pharmacist', 'Pharmacist / Dispensing Staff'), ('accountant', 'Accountant / Cashier')], db_index=True, default='receptionist', max_length=24),
        ),
    ]
