# Generated by Django 4.2.23 on 2026-08-22 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('resource_type', models.CharField(db_index=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('view_clinic_audit', 'Can view clinic audit history')],
            },
        ),
        migrations.CreateModel(
            name='ClinicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/branding/')),
                ('address', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=50)),
                ('receipt_prefix', models.CharField(default='RCP', max_length=12)),
                ('patient_number_prefix', models.CharField(default='EC', max_length=12)),
                ('appointment_number_prefix', models.CharField(default='APT', max_length=12)),
                ('visit_number_prefix', models.CharField(default='VIS', max_length=12)),
                ('appointment_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('default_prescription_validity_days', models.PositiveSmallIntegerField(default=365)),
                ('sms_sender_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic configuration',
                'verbose_name_plural': 'Clinic configuration',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=24, unique=True)),
                ('role', models.CharField(choices=[('system_admin', 'System Administrator'), ('clinic_admin', 'Clinic Administrator'), ('optometrist', 'Optometrist'), ('ophthalmologist', 'Ophthalmologist'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('optician', 'Optician'), ('pharmacist', 'Pharmacist / Dispensing Staff'), ('accountant', 'Accountant / Cashier')], db_index=True, max_length=24)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('professional_title', models.CharField(blank=True, max_length=80)),
                ('registration_number', models.CharField(blank=True, max_length=80)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'staff_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clinicconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='clinic_single_active_configuration'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
